GabrielBargas.Clientes.Mvc/Controllers/ClienteController.cs
using GabrielBargas.Clientes.Business.Enums;
using GabrielBargas.Clientes.Database.Banco;
using GabrielBargas.Clientes.Database.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GabrielBargas.Clientes.Mvc.Controllers
{
    public class ClienteController : Controller
    {
        #region Parametros

        private readonly IClienteData IClienteData;
        private readonly ISegmentoData ISegmentoData;
        private readonly IEnderecoData IEnderecoData;
        private readonly IHistorico_RelacionamentoData IHistoricoRelacionamento;

        #endregion

        #region Construtor

        public ClienteController(IClienteData _IClienteData,ISegmentoData _ISegmentoData,IEnderecoData _IEnderecoData, IHistorico_RelacionamentoData _IHistoricoRelacionamento)
        {
            this.IClienteData = _IClienteData;
            this.ISegmentoData = _ISegmentoData;
            this.IEnderecoData = _IEnderecoData;
            this.IHistoricoRelacionamento = _IHistoricoRelacionamento;
        }

        #endregion

        #region Metodos Publicos
        
        // GET: Cliente
        public ActionResult Index()
        {
            var clientes = IClienteData.ListarClientes();
            return View(clientes);
        }

        // GET: Cliente/Details/5
        public ActionResult Details(int id)
        {

            var clienteSelecionado = IClienteData.BuscarCliente(id);
            var segmento = ISegmentoData.BuscarSegmento((int)clienteSelecionado.ID_SEGMENTO);
            var histRelacionamento = IHistoricoRelacionamento.ListarHistoricoRelacionamentosCliente(clienteSelecionado.ID_CLIENTE);


            ViewBag.Endereco = IEnderecoData.ListarEnderecosCliente(clienteSelecionado.ID_CLIENTE);
            ViewBag.SegmentoDescricao = segmento.DESCRICAO;
            ViewBag.HistoricoRelacionamento = histRelacionamento.OrderByDescending(s => s.DATA_HISTORICO).ToList();

            return View(clienteSelecionado);
        }

        // GET: Cliente/Create
        public ActionResult Create()
        {
            var tipoClassificao = from TipoClassificacao e in Enum.GetValues(typeof(TipoClassificacao))
                                  select new
                                  {
                                      Id = (char)e,
                                      Descricao = e.ToString()
                                  };

            ViewBag.TipoClassificaçao = new SelectList(tipoClassificao, "ID", "Descricao");
            ViewBag.Segmentos = new SelectList(ISegmentoData.ListarSegmentos(), "ID_SEGMENTO", "DESCRICAO");

            return View();
        }

        // POST: Cliente/Create
        [HttpPost]
        public ActionResult Create(CLIENTE cliente)
        {
            try
            {
                cliente = PuxarDadosDropdown(cliente);

                IClienteData.CadastrarCliente(cliente);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Cliente/Edit/5
        public ActionResult Edit(int id)
        {
            var clienteSelecionado = IClienteData.BuscarCliente(id);

            var tipoClassificao = from TipoClassificacao e in Enum.GetValues(typeof(TipoClassificacao))
                                  select new
                                  {
                                      Id = (char)e,
                                      Descricao = e.ToString()
                                  };

            ViewBag.TipoClassificaçao = new SelectList(tipoClassificao, "Id", "Descricao",clienteSelecionado.CLASSIFICACAO);
            ViewBag.Segmentos = new SelectList(ISegmentoData.ListarSegmentos(), "ID_SEGMENTO", "DESCRICAO",clienteSelecionado.ID_SEGMENTO);

            
            return View(clienteSelecionado);
        }

        // POST: Cliente/Edit/5
        [HttpPost]
        public ActionResult Edit(CLIENTE cliente,bool FlagInativo = false)
        {
            try
            {
                cliente = PuxarDadosDropdown(cliente);

                IClienteData.AtualizarCliente(cliente,FlagInativo);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public void InativarCliente(int id)
        {
            try
            {
                bool flagInativo = true;

                IClienteData.InativarCliente(id,flagInativo);

                RedirectToAction("Index");
            }
            catch
            {
                RedirectToAction("Index");
            }
        }

        #endregion

        #region Metodos Privados

        private CLIENTE PuxarDadosDropdown(CLIENTE cliente)
        {
            string idSegmento = Request.Form["Segmentos"].ToString();
            string tipoClassificacao = Request.Form["TipoClassificaçao"].ToString();

            cliente.ID_SEGMENTO = Convert.ToInt32(idSegmento);
            cliente.CLASSIFICACAO = tipoClassificacao;

            return cliente;
        }
        
        #endregion
    }
}

GabrielBargas.Clientes.Mvc/Controllers/EnderecoController.cs
using GabrielBargas.Clientes.Business.Enums;
using GabrielBargas.Clientes.Database.Banco;
using GabrielBargas.Clientes.Database.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GabrielBargas.Clientes.Mvc.Controllers
{
    public class EnderecoController : Controller
    {
        #region Parametros

        private readonly IClienteData IClienteData;
        private readonly ISegmentoData ISegmentoData;
        private readonly IEnderecoData IEnderecoData;

        #endregion

        #region Construtor

        public EnderecoController(IClienteData _IClienteData, ISegmentoData _ISegmentoData, IEnderecoData _IEnderecoData)
        {
            this.IClienteData = _IClienteData;
            this.ISegmentoData = _ISegmentoData;
            this.IEnderecoData = _IEnderecoData;
        }

        #endregion

        #region Metodos publicos
        // GET: Endereco
        public ActionResult Index()
        {
            return View();
        }

        // GET: Endereco/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Endereco/Create
        public ActionResult Create(int idCliente)
        {
            var tipoEndereco= from TipoEndereco e in Enum.GetValues(typeof(TipoEndereco))
                                  select new
                                  {
                                      Id = (char)e,
                                      Descricao = e.ToString()
                                  };
            ViewBag.TipoEndereco = new SelectList(tipoEndereco, "Id", "Descricao");

            ENDERECO endereco = new ENDERECO();
            endereco.ID_CLIENTE = idCliente;

            return View(endereco);
        }

        // POST: Endereco/Create
        [HttpPost]
        public ActionResult Create(ENDERECO endereco)
        {
            try
            {
                string tipoEndereco = Request.Form["tipoEndereco"].ToString();
                endereco.TIPO_ENDERECO = tipoEndereco;
                IEnderecoData.CadastrarEndereco(endereco);

                return RedirectToAction("Details", "Cliente", new { id = endereco.ID_CLIENTE });
            }
            catch
            {
                return RedirectToAction("Details", "Cliente", new { id = Convert.ToInt32(endereco.ID_CLIENTE) });
            }
        }

        // GET: Endereco/Edit/5
        public ActionResult Edit(int id)
        {
            var tipoEndereco = from TipoEndereco e in Enum.GetValues(typeof(TipoEndereco))
                               select new
                               {
                                   Id = (char)e,
                                   Descricao = e.ToString()
                               };
            

            var endereco = IEnderecoData.BuscarEndereco(id);

            ViewBag.TipoEndereco = new SelectList(tipoEndereco, "Id", "Descricao",endereco.TIPO_ENDERECO);

            return View(endereco);
        }

        // POST: Endereco/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, ENDERECO endereco)
        {
            try
            {
                string tipoEndereco = Request.Form["tipoEndereco"].ToString();
                endereco.TIPO_ENDERECO = tipoEndereco;

                IEnderecoData.AlterarEndereco(endereco);

                return RedirectToAction("Details", "Cliente", new { id = endereco.ID_CLIENTE });

            }
            catch
            {
                return View("Details", "Cliente", new { id = Convert.ToInt32(endereco.ID_CLIENTE) });
            }
        }

        // GET: Endereco/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Endereco/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        #endregion
    }
}

GabrielBargas.Clientes.Mvc/Controllers/HistoricoRelacionamentoController.cs
using GabrielBargas.Clientes.Database.Banco;
using GabrielBargas.Clientes.Database.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GabrielBargas.Clientes.Mvc.Controllers
{
    public class HistoricoRelacionamentoController : Controller
    {
        #region Parametros

        private readonly IClienteData IClienteData;
        private readonly IHistorico_RelacionamentoData IHistoricoRelacionamentoData;

        #endregion

        #region Construtor

        public HistoricoRelacionamentoController(IClienteData _IClienteData, IHistorico_RelacionamentoData _IHistoricoRelacionamentoData)
        {
            this.IClienteData = _IClienteData;
            this.IHistoricoRelacionamentoData = _IHistoricoRelacionamentoData;
        }

        #endregion
        // GET: HistoricoRelacionamento
        public ActionResult Index()
        {
            return View();
        }

        // GET: HistoricoRelacionamento/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: HistoricoRelacionamento/Create
        public ActionResult Create(int idCliente)
        {
            HISTORICO_RELACIONAMENTO histRelacionamento = new HISTORICO_RELACIONAMENTO();
            histRelacionamento.ID_CLIENTE = idCliente;

            return View(histRelacionamento); ;
        }

        // POST: HistoricoRelacionamento/Create
        [HttpPost]
        public ActionResult Create(HISTORICO_RELACIONAMENTO histRelacionamento)
        {
            try
            {
                histRelacionamento.DATA_HISTORICO = DateTime.Now;

                IHistoricoRelacionamentoData.CadastrarHistoricoRelacionamento(histRelacionamento);

                return RedirectToAction("Details", "Cliente", new { id = histRelacionamento.ID_CLIENTE });
            }
            catch
            {
                return RedirectToAction("Details", "Cliente", new { id = histRelacionamento.ID_CLIENTE });
            }
        }

        // GET: HistoricoRelacionamento/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: HistoricoRelacionamento/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: HistoricoRelacionamento/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: HistoricoRelacionamento/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

GabrielBargas.Clientes.Mvc/Views/Cliente/Create.cshtml
@model GabrielBargas.Clientes.Database.Banco.CLIENTE
@using GabrielBargas.Clientes.Database.Banco
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CLIENTE</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NOME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CPF_CNPJ, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPF_CNPJ, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CPF_CNPJ, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TEL_PRINCIPAL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TEL_PRINCIPAL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TEL_PRINCIPAL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TEL_ALTERNATIVO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TEL_ALTERNATIVO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TEL_ALTERNATIVO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CLASSIFICACAO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Tipo de classificaçao", ViewBag.TipoClassificaçao as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CLASSIFICACAO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_SEGMENTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Segmentos",ViewBag.Segmentos as SelectList,htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_SEGMENTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GabrielBargas.Clientes.Mvc/Views/Cliente/Details.cshtml
@model GabrielBargas.Clientes.Database.Banco.CLIENTE
@using GabrielBargas.Clientes.Database.Banco
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
@Html.HiddenFor(model => model.ID_CLIENTE)
<div>
    <h4>CLIENTE</h4>
    <hr />
    <dl class="dl-horizontal">


        <dt>
            Nome
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOME)
        </dd>

        <dt>
            CPF/CNPJ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CPF_CNPJ)
        </dd>

        <dt>
            Telefone Principal
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TEL_PRINCIPAL)
        </dd>

        @if (Model.TEL_ALTERNATIVO != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.TEL_ALTERNATIVO)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TEL_ALTERNATIVO)
            </dd>
        }

        <dt>
            Classificação
        </dt>
        @if (Convert.ToChar(Model.CLASSIFICACAO) == 'O')
        {
            <dd>
                Ouro
            </dd>
        }
        @if (Convert.ToChar(Model.CLASSIFICACAO) == 'P')
        {
            <dd>
                Prata
            </dd>
        }
        @if (Convert.ToChar(Model.CLASSIFICACAO) == 'B')
        {
            <dd>
                Bronze
            </dd>
        }
        <dt>
            Segmento
        </dt>

        <dd>
            @ViewBag.SegmentoDescricao
        </dd>

    </dl>
    <div class="panel panel-primary">
        <div class="panel-heading">Endereços</div>
        <div class="panel-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Rua</th>
                        <th>Numero</th>
                        <th>Cidade</th>
                        <th>Estado</th>
                        <th>Tipo de endereço</th>
                        <th>Editar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var e in ViewBag.Endereco as List<ENDERECO>)
                    {
                        <tr>
                            <td> @e.RUA</td>
                            <td> @e.NUMERO</td>
                            <td> @e.CIDADE</td>
                            <td> @e.ESTADO</td>
                            @if (Convert.ToChar(e.TIPO_ENDERECO) == 'A')
                            {
                                <td>Alternativo</td>
                            }
                            @if (Convert.ToChar(e.TIPO_ENDERECO) == 'P')
                            {
                                <td>Principal</td>
                            }

                            <td class="col-md-3">@Html.ActionLink("Editar", "Edit", "Endereco", new { id = e.ID_ENDERECO }, null)</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="panel-footer">
            @Html.ActionLink("Cadastrar Endereco", "Create", "Endereco", new { idCliente = Model.ID_CLIENTE }, null)
        </div>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">Historico de relacionamento</div>
        <div class="panel-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Data</th>
                        <th>Descricao</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var e in ViewBag.HistoricoRelacionamento as List<HISTORICO_RELACIONAMENTO>)
                    {
                        <tr>
                            <td> @e.DATA_HISTORICO</td>
                            <td> @e.DESCRICAO</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="panel-footer">
            @Html.ActionLink("Cadastrar Historico", "Create", "HistoricoRelacionamento", new { idCliente = Model.ID_CLIENTE }, null)
        </div>
    </div>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ID_CLIENTE }) |
    @Html.ActionLink("Lista de Clientes", "Index")
</p>

GabrielBargas.Clientes.Mvc/Views/Cliente/Edit.cshtml
@model GabrielBargas.Clientes.Database.Banco.CLIENTE

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>CLIENTE</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID_CLIENTE)
    <div class="form-group">
        @Html.LabelFor(model => model.NOME, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NOME, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NOME, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CPF_CNPJ, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CPF_CNPJ, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CPF_CNPJ, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TEL_PRINCIPAL, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TEL_PRINCIPAL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TEL_PRINCIPAL, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TEL_ALTERNATIVO, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TEL_ALTERNATIVO, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TEL_ALTERNATIVO, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CLASSIFICACAO, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("TipoClassificaçao", ViewBag.TipoClassificaçao as SelectList, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CLASSIFICACAO, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ID_SEGMENTO, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Segmentos", ViewBag.Segmentos as SelectList, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ID_SEGMENTO, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("INATIVAR CLIENTE", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.CheckBox("FlagInativo",false, htmlAttributes: new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GabrielBargas.Clientes.Mvc/Views/Cliente/Index.cshtml
@model IEnumerable<GabrielBargas.Clientes.Database.Banco.CLIENTE>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            id do Cliente
        </th>
        <th>
            Nome
        </th>
        <th>
            CPF/CNPJ
        </th>
        <th>
            Telefone principal
        </th>
        <th>
            Telefone Alternativo
        </th>
        <th>
            Classificação
        </th>
        <th>
            Segmento
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID_CLIENTE)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NOME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CPF_CNPJ)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TEL_PRINCIPAL)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TEL_ALTERNATIVO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CLASSIFICACAO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ID_SEGMENTO)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.ID_CLIENTE }) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.ID_CLIENTE }) |
            </td>
        </tr>
    }

</table>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/Views/Cliente/Metodos.js")
}